"""
Automated Validator Module

This module provides functionality to validate a complete sequence of moves
for the Tower of Hanoi puzzle, useful for evaluating reasoning model outputs.
"""

from puzzles.hanoi_tower.hanoi_state import HanoiState
from typing import List, Tuple, Dict, Any, Optional
import json


class AutomatedValidator:
    """
    Validates a complete sequence of moves for Tower of Hanoi puzzle.
    Useful for evaluating solutions generated by reasoning models.
    """

    def __init__(self, n_disks: int):
        """
        Initialize the automated validator.

        Args:
            n_disks: Number of disks in the puzzle
        """
        self.n_disks = n_disks
        self.state = HanoiState(n_disks)

    def validate_solution(self, moves: List[List[int]], verbose: bool = True) -> Dict[str, Any]:
        """
        Validate a sequence of moves.

        Args:
            moves: List of moves in format [[disk, from_peg, to_peg], ...]
            verbose: If True, print detailed information during validation

        Returns:
            Dictionary containing validation results:
                - is_valid: bool - Whether the solution is valid
                - is_solved: bool - Whether the puzzle was solved
                - total_moves: int - Number of moves in the sequence
                - valid_moves: int - Number of valid moves applied
                - failed_at: int or None - Index of first failed move (None if all valid)
                - error_message: str - Error message if validation failed
                - optimal_moves: int - Optimal number of moves for this puzzle
                - efficiency: float - Ratio of optimal to actual moves
        """
        # Reset state
        self.state.reset()

        if verbose:
            print("\n" + "="*60)
            print("  TOWER OF HANOI - AUTOMATED VALIDATOR")
            print("="*60)
            print(f"\nValidating solution for {self.n_disks}-disk puzzle...")
            print(f"Total moves to validate: {len(moves)}\n")

        # Validate each move
        for i, move in enumerate(moves):
            # Validate move format
            if not isinstance(move, list) or len(move) != 3:
                error_msg = f"Invalid move format at step {i+1}: {move}. Expected [disk, from_peg, to_peg]"
                if verbose:
                    print(f"❌ {error_msg}")
                return self._create_result(
                    is_valid=False,
                    failed_at=i,
                    error_message=error_msg
                )

            disk, from_peg, to_peg = move

            if verbose:
                print(f"Step {i+1}: Move disk {disk} from peg {from_peg} to peg {to_peg}")
                print(f"  Before: {self.state.pegs}")

            # Apply move
            success, message = self.state.apply_move(disk, from_peg, to_peg)

            if not success:
                error_msg = f"Invalid move at step {i+1}: {message}"
                if verbose:
                    print(f"  After:  {self.state.pegs}")
                    print(f"  ❌ {error_msg}\n")
                return self._create_result(
                    is_valid=False,
                    failed_at=i,
                    error_message=error_msg
                )

            if verbose:
                print(f"  After:  {self.state.pegs}")
                print(f"  ✓ Valid move\n")

        # All moves valid, check if solved
        if verbose:
            print("-"*60)
            if self.state.is_solved:
                print("✓ Solution is VALID and puzzle is SOLVED!")
            else:
                print("⚠ All moves are valid, but puzzle is NOT solved")
            print("-"*60 + "\n")

        return self._create_result(
            is_valid=True,
            failed_at=None,
            error_message=""
        )

    def _create_result(self, is_valid: bool, failed_at: Optional[int],
                      error_message: str) -> Dict[str, Any]:
        """
        Create a result dictionary.

        Args:
            is_valid: Whether all moves were valid
            failed_at: Index of first failed move (None if all valid)
            error_message: Error message if validation failed

        Returns:
            Dictionary with validation results
        """
        optimal_moves = 2**self.n_disks - 1
        efficiency = optimal_moves / self.state.num_moves if self.state.num_moves > 0 else 0

        return {
            'is_valid': is_valid,
            'is_solved': self.state.is_solved,
            'total_moves': len(self.state.history),
            'valid_moves': self.state.num_moves,
            'failed_at': failed_at,
            'error_message': error_message,
            'optimal_moves': optimal_moves,
            'efficiency': efficiency,
            'final_state': self.state.get_state(),
            'move_history': self.state.history.copy()
        }

    def validate_from_file(self, filepath: str, verbose: bool = True) -> Dict[str, Any]:
        """
        Validate moves from a JSON file.

        Args:
            filepath: Path to JSON file containing moves
            verbose: If True, print detailed information

        Returns:
            Dictionary containing validation results
        """
        try:
            with open(filepath, 'r') as f:
                data = json.load(f)

            # Support multiple formats
            if isinstance(data, dict) and 'moves' in data:
                moves = data['moves']
                if 'n_disks' in data and data['n_disks'] != self.n_disks:
                    return {
                        'is_valid': False,
                        'error_message': f"File specifies {data['n_disks']} disks, but validator initialized with {self.n_disks}"
                    }
            elif isinstance(data, list):
                moves = data
            else:
                return {
                    'is_valid': False,
                    'error_message': "Invalid file format. Expected list of moves or dict with 'moves' key"
                }

            return self.validate_solution(moves, verbose)

        except FileNotFoundError:
            return {
                'is_valid': False,
                'error_message': f"File not found: {filepath}"
            }
        except json.JSONDecodeError as e:
            return {
                'is_valid': False,
                'error_message': f"Invalid JSON: {e}"
            }
        except Exception as e:
            return {
                'is_valid': False,
                'error_message': f"Error reading file: {e}"
            }

    def print_summary(self, result: Dict[str, Any]):
        """
        Print a formatted summary of validation results.

        Args:
            result: Result dictionary from validate_solution
        """
        print("\n" + "="*60)
        print("  VALIDATION SUMMARY")
        print("="*60)

        if not result.get('is_valid', False):
            print(f"\n❌ INVALID SOLUTION")
            print(f"\nError: {result.get('error_message', 'Unknown error')}")
            if result.get('failed_at') is not None:
                print(f"Failed at move: {result['failed_at'] + 1}")
            print(f"Valid moves applied: {result.get('valid_moves', 0)}")
        else:
            print(f"\n✓ ALL MOVES VALID")
            if result['is_solved']:
                print(f"✓ PUZZLE SOLVED")
            else:
                print(f"⚠ PUZZLE NOT SOLVED (but all moves are valid)")

            print(f"\nTotal moves: {result['total_moves']}")
            print(f"Optimal moves: {result['optimal_moves']}")
            print(f"Efficiency: {result['efficiency']:.2%}")

            if result['efficiency'] == 1.0:
                print("\n⭐ OPTIMAL SOLUTION!")
            elif result['efficiency'] >= 0.67:
                print("\n👍 Good solution!")
            else:
                print("\n💡 Could be more efficient")

        print("\n" + "="*60 + "\n")


def main():
    """Main function for automated validator."""
    print("\nTower of Hanoi - Automated Validator")
    print("="*60)

    # Example usage
    print("\nExample 1: Validate a 3-disk solution")
    print("-"*60)

    # Optimal solution for 3 disks
    moves_3_disk = [
        [1, 0, 2],  # Move disk 1 from peg 0 to peg 2
        [2, 0, 1],  # Move disk 2 from peg 0 to peg 1
        [1, 2, 1],  # Move disk 1 from peg 2 to peg 1
        [3, 0, 2],  # Move disk 3 from peg 0 to peg 2
        [1, 1, 0],  # Move disk 1 from peg 1 to peg 0
        [2, 1, 2],  # Move disk 2 from peg 1 to peg 2
        [1, 0, 2],  # Move disk 1 from peg 0 to peg 2
    ]

    validator = AutomatedValidator(n_disks=3)
    result = validator.validate_solution(moves_3_disk, verbose=True)
    validator.print_summary(result)

    # Example with invalid move
    print("\nExample 2: Validate an invalid solution")
    print("-"*60)

    invalid_moves = [
        [1, 0, 2],
        [3, 0, 1],  # Invalid: disk 3 is not on top of peg 0
    ]

    validator2 = AutomatedValidator(n_disks=3)
    result2 = validator2.validate_solution(invalid_moves, verbose=True)
    validator2.print_summary(result2)


if __name__ == "__main__":
    main()
